import type { LibraryExercise } from './types'

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  { name: 'Bench Press', aliases: ['barbell bench', 'bench'] },
  { name: 'Incline Bench Press', aliases: ['incline bench'] },
  {
    name: 'Incline Barbell Bench Press',
    aliases: ['incline bench', 'incline barbell bench', 'bb incline bench'],
  },
  {
    name: 'Incline Dumbbell Press',
    aliases: ['incline db press', 'incline press', 'incline bench'],
  },
  { name: 'Dumbbell Bench Press', aliases: ['db bench'] },
  { name: 'Chest Press Machine', aliases: ['machine press'] },
  { name: 'Chest Fly', aliases: ['pec fly', 'pec deck', 'dumbbell fly'] },
  { name: 'Pec Deck Fly', aliases: ['pec fly', 'pec deck', 'chest fly'] },
  { name: 'Push-Up', aliases: ['pushup', 'press up'] },
  { name: 'Dips', aliases: ['chest dip', 'tricep dip'] },
  { name: 'Chest Dips', aliases: ['chest dip', 'dips', 'tricep dip'] },
  { name: 'Pull-Up', aliases: ['pullup', 'chin-up', 'chin up'] },
  {
    name: 'Weighted Pull-Ups',
    aliases: ['weighted pull up', 'pull up', 'pullups', 'weighted chin-up'],
  },
  { name: 'Lat Pulldown', aliases: ['lat pull down', 'pulldown'] },
  {
    name: 'Straight Arm Pull Down',
    aliases: ['straight arm pulldown', 'straight arm lat pulldown'],
  },
  { name: 'Seated Cable Row', aliases: ['cable row', 'seated row'] },
  {
    name: 'One Arm Seated Cable Row',
    aliases: ['one arm cable row', 'single arm cable row', 'seated cable row'],
  },
  { name: 'Barbell Row', aliases: ['bent over row', 'barbell bent over row'] },
  {
    name: 'Bent Over Barbell Row',
    aliases: ['bent over row', 'barbell bent over row', 'barbell row'],
  },
  { name: 'Dumbbell Row', aliases: ['db row', 'one arm row'] },
  { name: 'T-Bar Row', aliases: [] },
  { name: 'Face Pull', aliases: ['rear delt face pull'] },
  { name: 'Face Pulls', aliases: ['face pull', 'rear delt face pull'] },
  { name: 'Rear Delt Fly', aliases: ['reverse fly', 'reverse pec deck'] },
  { name: 'Squat', aliases: ['barbell squat', 'back squat'] },
  { name: 'Smith Squat', aliases: ['smith machine squat'] },
  { name: 'Front Squat', aliases: [] },
  { name: 'Leg Press', aliases: ['leg press machine'] },
  { name: 'Leg Extension', aliases: ['quad extension'] },
  { name: 'Leg Curl', aliases: ['hamstring curl', 'lying leg curl', 'seated leg curl'] },
  {
    name: 'Leg Curl Machine',
    aliases: ['leg curl', 'hamstring curl', 'seated leg curl'],
  },
  { name: 'Romanian Deadlift', aliases: ['rdl', 'romanian deadlift'] },
  { name: 'Deadlift', aliases: ['conventional deadlift'] },
  { name: 'Lunge', aliases: ['walking lunge', 'reverse lunge'] },
  { name: 'Bulgarian Split Squat', aliases: ['split squat'] },
  { name: 'Hip Thrust', aliases: ['glute bridge', 'barbell hip thrust'] },
  { name: 'Calf Raise', aliases: ['standing calf raise', 'seated calf raise'] },
  { name: 'Overhead Press', aliases: ['ohp', 'military press', 'shoulder press'] },
  { name: 'Dumbbell Shoulder Press', aliases: ['db press', 'seated shoulder press'] },
  { name: 'Lateral Raise', aliases: ['side raise', 'side lateral raise'] },
  { name: 'Cable Lateral Raise', aliases: ['cable side raise', 'lateral raise', 'side lateral raise'] },
  { name: 'Front Raise', aliases: [] },
  { name: 'Shrug', aliases: ['dumbbell shrug', 'barbell shrug'] },
  {
    name: 'Dumbbell / Barbell Shrugs',
    aliases: ['shrug', 'dumbbell shrug', 'barbell shrug'],
  },
  { name: 'Bicep Curl', aliases: ['barbell curl', 'dumbbell curl'] },
  { name: 'Incline Dumbbell Curls', aliases: ['incline db curl', 'incline curl'] },
  { name: 'Hammer Curl', aliases: [] },
  { name: 'Hammer Curls', aliases: ['hammer curl', 'db hammer curl'] },
  { name: 'Preacher Curl', aliases: [] },
  { name: 'Preacher Curls', aliases: ['preacher curl', 'ez bar preacher curl'] },
  { name: 'Reverse Barbell Curls', aliases: ['reverse curl', 'reverse barbell curl'] },
  { name: 'Tricep Pushdown', aliases: ['cable pushdown', 'pushdown'] },
  { name: 'Triceps Pushdown', aliases: ['tricep pushdown', 'cable pushdown', 'pushdown'] },
  { name: 'Skull Crusher', aliases: ['lying tricep extension'] },
  { name: 'Overhead Tricep Extension', aliases: ['tricep extension'] },
  {
    name: 'Triceps Overhead Extension',
    aliases: ['overhead tricep extension', 'tricep extension', 'overhead extension'],
  },
  { name: 'Kettlebell Swing', aliases: ['kb swing'] },
  { name: 'Good Morning', aliases: [] },
  { name: 'Back Extension', aliases: ['hyperextension'] },
  { name: 'Crunch', aliases: ['sit up', 'situp'] },
  { name: 'Plank', aliases: ['front plank'] },
  { name: 'Hanging Leg Raise', aliases: ['leg raise', 'hanging knee raise'] },
  { name: 'Russian Twist', aliases: [] },
  { name: 'Cable Crunch', aliases: ['kneeling crunch'] },
  { name: 'Burpee', aliases: [] },
  { name: 'Mountain Climber', aliases: [] },
  { name: 'Step-Up', aliases: [] },
  { name: "Farmer's Carry", aliases: ['farmer walk'] },
  { name: 'Pullover', aliases: ['dumbbell pullover'] },
]